### ISSUE TITLE
python faceboom.py -t Victim@gmail.com -w /usr/share/wordlists/rockyou.txt

### ISSUE THREAD

**Issue by EhabEllawendy** [Oseid/FaceBoom#19]
Traceback (most recent call last):
  File "/root/FaceBoom/faceboom.py", line 269, in <module>
    Main()
  File "/root/FaceBoom/faceboom.py", line 239, in Main
    loop,passwords = (1,open(wordlist).readlines()) if not single_passwd else ("~",[single_passwd])
  File "/usr/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 933: invalid continuation byte

**Comment by Oseid** [comment]
@EhabEllawendy 
This problem have been solved please **update** the script :)
