### ISSUE TITLE
NameError: name 'faceBoom' is not defined

### ISSUE THREAD

**Issue by mth-bou** [Oseid/FaceBoom#21]
Traceback (most recent call last):
  File "/home/kali/Documents/FaceBoom/faceboom.py", line 274, in <module>
    Main()
  File "/home/kali/Documents/FaceBoom/faceboom.py", line 229, in Main
    if faceBoom.check_proxy(final_proxy):
NameError: name 'faceBoom' is not defined

**Comment by Oseid** [comment]
@mth-bou
this problem have been solved please update the script :)

**Comment by GdSithu** [comment]
> Traceback (most recent call last):
>   File "/home/kali/Documents/FaceBoom/faceboom.py", line 274, in <module>
>     Main()
>   File "/home/kali/Documents/FaceBoom/faceboom.py", line 229, in Main
>     if faceBoom.check_proxy(final_proxy):
> NameError: name 'faceBoom' is not defined
