### ISSUE TITLE
error

### ISSUE THREAD

**Issue by nithinjujuri** [Oseid/FaceBoom#23]
=================================
[---]        FaceBoom        [---]
==================================
[---]  BruteForce Facebook   [---]
==================================
[---]         CONFIG         [---]
==================================
[>] Target      :> Victim@gmail.com
[>] Wordlist    :> /usr/share/wordlists/rockyou.txt.gz
[>] ProxyStatus :> [OFF]
==================================
[~] Brute ForceATTACK: Enabled [~]
==================================

Traceback (most recent call last):
  File "faceboom.py", line 274, in <module>
    Main()
  File "faceboom.py", line 243, in Main
    with open(wordlist, 'r', errors='replace') as f:
TypeError: 'errors' is an invalid keyword argument for this function

**Comment by Oseid** [comment]
Hello @nithinjujuri
 
first please update the script using

```bash
python faceboom.py --update
```
then you have to unzip the wordlist first, to do that run this command
```bash
gzip -d /usr/share/wordlists/rockyou.txt.gz
```
then try again using 
python faceboom.py -t Victim@gmail.com -w /usr/share/wordlists/rockyou.txt
